contentdil = "content"
publishdir = "public"
baseurl = "https://supermil.ch/"
theme = "hugo-nuo"
title = "Manu Wallner"
languageCode = "en-us"
enableRobotsTXT = true

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-86164156-1"

# Define how many posts should appear on a site
paginate = 5

# Copyright of your post
copyright = "Â© 2017 Manu Wallner"

[params]
	author = "Manu Wallner"
	avatar = "/images/headshot.jpg"
	subtitle = "Software engineer mostly working on mobile apps. Jack of all trades, master of none. fastlane core contributor ðŸš€"
	description = "This is my personal website"

	# Format dates with Go's time formatting
	date_format = "2016-10-21"

	# The icons will be shown if you enter your username
	twitter = "acrooow"
	github = "milch"
	linkedin = "milch"
	email = "contact@supermil.ch"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Blog"
	url  = "/"
	weight = 5
